name: Pull Request Checks

on:
  pull_request:

jobs:
  unit-tests:
    name: Jest Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Npm install
        run: npm install
      - name: Install nx
        run: npm install -g nx
      - name: Unit test core
        run: nx test core
