name: Bump Version and Create Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: list tags
        run: git tag
      - name: Install dependencies
        run: npm ci
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Bump Version
        run: npm run bumpVersion:ci
      # there is some quirkiness here, but some files are modified that don't pass formatting standards, so force formatting & ammend
      # But when ammending commit tag is thrown off, so re-apply tag too
      - name: Format Files
        run: npm run format:fix
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Commit Files
        run: |
          git add -A
          git commit --amend --no-edit
          git tag -f v${{ steps.package-version.outputs.current-version }}
      # TODO update so that bot can push to main, or PR and auto merge to main (look for existing action to help)
      - name: Push changes (manual)
        run: git push origin ${{ github.ref }}
      - name: Push tag (manual)
        run: git push origin v${{ steps.package-version.outputs.current-version }}
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # prerelease: true
          # draft: true
          generateReleaseNotes: true
          tag: v${{ steps.package-version.outputs.current-version }}
